version: '3'
services:
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  server:
    build: ./server
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - '3003:3001'

volumes:
  mongodata:
